title = "P R A K U S H"

[params.author]
   name = "Prakush Ram"
   image = "prakush1.jpg"
   headline = "*योगः कर्मसु कौशलम्।*"
   bio = "I Speak the Language of Systems" # appears in author card for each article
   links = [
  { twitter = "https://twitter.com/PRAKUSH2611/" },
  { github = "https://github.com/Prashant0313/" },
  { linkedin = "https://linkedin.com/in/prashant-kush/" },
  { instagram = "https://www.instagram.com/prakush_26/" },
]